# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_pb2 as calculator__pb2


class CalculateServicerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.calculate = channel.unary_unary(
        '/calculator.CalculateServicer/calculate',
        request_serializer=calculator__pb2.CalculatorParameter.SerializeToString,
        response_deserializer=calculator__pb2.CalculatorResult.FromString,
        )


class CalculateServicerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def calculate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculateServicerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'calculate': grpc.unary_unary_rpc_method_handler(
          servicer.calculate,
          request_deserializer=calculator__pb2.CalculatorParameter.FromString,
          response_serializer=calculator__pb2.CalculatorResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'calculator.CalculateServicer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
