# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='calculator',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63\x61lculator.proto\x12\ncalculator\"\xb7\x01\n\x13\x43\x61lculatorParameter\x12\x10\n\x08operandA\x18\x01 \x01(\x01\x12\x10\n\x08operandB\x18\x02 \x01(\x01\x12>\n\x08operCode\x18\x03 \x01(\x0e\x32,.calculator.CalculatorParameter.OperatorCode\"<\n\x0cOperatorCode\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\t\n\x05MINUS\x10\x01\x12\x0c\n\x08MULTIPLY\x10\x02\x12\n\n\x06\x44IVIDE\x10\x03\"\"\n\x10\x43\x61lculatorResult\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32\x61\n\x11\x43\x61lculateServicer\x12L\n\tcalculate\x12\x1f.calculator.CalculatorParameter\x1a\x1c.calculator.CalculatorResult\"\x00\x62\x06proto3')
)



_CALCULATORPARAMETER_OPERATORCODE = _descriptor.EnumDescriptor(
  name='OperatorCode',
  full_name='calculator.CalculatorParameter.OperatorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MINUS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTIPLY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIVIDE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=156,
  serialized_end=216,
)
_sym_db.RegisterEnumDescriptor(_CALCULATORPARAMETER_OPERATORCODE)


_CALCULATORPARAMETER = _descriptor.Descriptor(
  name='CalculatorParameter',
  full_name='calculator.CalculatorParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operandA', full_name='calculator.CalculatorParameter.operandA', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operandB', full_name='calculator.CalculatorParameter.operandB', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operCode', full_name='calculator.CalculatorParameter.operCode', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CALCULATORPARAMETER_OPERATORCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=216,
)


_CALCULATORRESULT = _descriptor.Descriptor(
  name='CalculatorResult',
  full_name='calculator.CalculatorResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='calculator.CalculatorResult.result', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=252,
)

_CALCULATORPARAMETER.fields_by_name['operCode'].enum_type = _CALCULATORPARAMETER_OPERATORCODE
_CALCULATORPARAMETER_OPERATORCODE.containing_type = _CALCULATORPARAMETER
DESCRIPTOR.message_types_by_name['CalculatorParameter'] = _CALCULATORPARAMETER
DESCRIPTOR.message_types_by_name['CalculatorResult'] = _CALCULATORRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalculatorParameter = _reflection.GeneratedProtocolMessageType('CalculatorParameter', (_message.Message,), dict(
  DESCRIPTOR = _CALCULATORPARAMETER,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.CalculatorParameter)
  ))
_sym_db.RegisterMessage(CalculatorParameter)

CalculatorResult = _reflection.GeneratedProtocolMessageType('CalculatorResult', (_message.Message,), dict(
  DESCRIPTOR = _CALCULATORRESULT,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.CalculatorResult)
  ))
_sym_db.RegisterMessage(CalculatorResult)



_CALCULATESERVICER = _descriptor.ServiceDescriptor(
  name='CalculateServicer',
  full_name='calculator.CalculateServicer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=254,
  serialized_end=351,
  methods=[
  _descriptor.MethodDescriptor(
    name='calculate',
    full_name='calculator.CalculateServicer.calculate',
    index=0,
    containing_service=None,
    input_type=_CALCULATORPARAMETER,
    output_type=_CALCULATORRESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATESERVICER)

DESCRIPTOR.services_by_name['CalculateServicer'] = _CALCULATESERVICER

# @@protoc_insertion_point(module_scope)
